version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - mkdir -p document-package bin-package
      - pip install -r src/functions/document-service/requirements.txt -t ./document-package || echo "No requirements.txt found"
      - pip install -r src/functions/bin-service/requirements.txt -t ./bin-package || echo "No requirements.txt found"

  build:
    commands:
      - echo Packaging Lambda functions...
      - mkdir -p deployment
      
      # Document Service
      - cp src/functions/document-service/handler.py ./document-package/
      - cd document-package
      - zip -r ../deployment/document-service-deployment-package.zip .
      - cd ..

      # Bin Service
      - cp src/functions/bin-service/handler.py ./document-package/
      - cd bin-package
      - zip -r ../deployment/bin-service-deployment-package.zip .
      - cd ..

  post_build:
    commands:
      - ls -la deployment/
      - aws s3 cp deployment/document-service-deployment-package.zip s3://${DEPLOYMENT_BUCKET}/${ENVIRONMENT_TYPE}/document-service/deployment-package.zip --acl private
      - aws s3 cp deployment/bin-service-deployment-package.zip s3://${DEPLOYMENT_BUCKET}/${ENVIRONMENT_TYPE}/bin-service/deployment-package.zip --acl private
      - echo "Files uploaded to S3"
      - aws lambda update-function-code --function-name wms-document-service-${ENVIRONMENT_TYPE} --s3-bucket ${DEPLOYMENT_BUCKET} --s3-key ${ENVIRONMENT_TYPE}/document-service/deployment-package.zip
      - aws lambda update-function-code --function-name wms-bin-service-${ENVIRONMENT_TYPE} --s3-bucket ${DEPLOYMENT_BUCKET} --s3-key ${ENVIRONMENT_TYPE}/bin-service/deployment-package.zip
      - echo "Lambda functions updated directly via AWS CLI"

artifacts:
  files:
    - infrastructure/wms-base-infrastructure.yaml
    - infrastructure/wms-storage-stack.yaml
    - infrastructure/wms-service-stack.yaml
    - appspec.yml
