version: 0.2

env:
  variables:
    # 환경 변수 설정
    DEPLOYMENT_BUCKET: "wms-deployment-dev-242201288894-us-east-2-wms-storage-stack-v1"
  
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - mkdir -p receiving-order-package
      - pip install -r src/functions/receiving-order-service/requirements.txt -t ./receiving-order-package || echo "No requirements.txt found"
  
  build:
    commands:
      - echo Packaging Lambda functions...
      - mkdir -p deployment
      
      # Receiving Order Service
      - echo "Copying Lambda function code..."
      - cp src/functions/receiving-order-service/ReceivingOrderService.py ./receiving-order-package/ || echo "ReceivingOrderService.py not found"
      - cd receiving-order-package
      - zip -r ../deployment/receiving-order-service-deployment-package.zip .
      - cd ..
      
      # 디버깅을 위한 추가 구성
      - echo "Contents of src/functions directory:"
      - ls -la src/functions/ || echo "src/functions directory not found"
      - echo "Contents of receiving-order-service directory (if exists):"
      - ls -la src/functions/receiving-order-service/ || echo "receiving-order-service directory not found"
  
  post_build:
    commands:
      - echo "Deployment directory contents:"
      - ls -la deployment/ || echo "Deployment directory is empty"
      
      # S3에 배포 패키지 업로드
      - echo "Uploading deployment package to S3 bucket: ${DEPLOYMENT_BUCKET}"
      - aws s3 cp deployment/receiving-order-service-deployment-package.zip s3://${DEPLOYMENT_BUCKET}/${ENVIRONMENT_TYPE}/receiving-order-service/deployment-package.zip --acl private || echo "Receiving order service upload failed"
      
      # 업로드 확인
      - echo "Verifying uploaded files:"
      - aws s3 ls s3://${DEPLOYMENT_BUCKET}/${ENVIRONMENT_TYPE}/receiving-order-service/ || echo "Failed to list objects in the bucket"
      
      # Lambda 함수 업데이트 (함수가 이미 존재하는 경우)
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name wms-receiving-order-service-${ENVIRONMENT_TYPE} --s3-bucket ${DEPLOYMENT_BUCKET} --s3-key ${ENVIRONMENT_TYPE}/receiving-order-service/deployment-package.zip || echo "Receiving order service update failed - function may not exist yet"
      
      # CloudFormation 템플릿 복사
      - echo "Copying CloudFormation templates to S3..."
      - aws s3 cp infrastructure/ s3://${DEPLOYMENT_BUCKET}/${ENVIRONMENT_TYPE}/infrastructure/ --recursive || echo "Infrastructure template upload failed"
      
      - echo "Build and deployment process completed"

artifacts:
  files:
    - deployment/**/*
    - infrastructure/**/*
    - buildspec.yml
    - README.md
  discard-paths: no