AWSTemplateFormatVersion: '2010-09-09'
Description: 'WMS Storage Infrastructure - Simplified'

Parameters:
  EnvironmentType:
    Description: Environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod

Resources:
  # 문서 저장을 위한 S3 버킷
  DocumentBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "wms-documents-${EnvironmentType}-${AWS::AccountId}-${AWS::Region}-${AWS::StackName}-v1"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveRule
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER
  
  # 문서 메타데이터 DynamoDB 테이블
  DocumentMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "wms-document-metadata-${EnvironmentType}-${AWS::StackName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: document_id
          AttributeType: S
        - AttributeName: order_id
          AttributeType: S
        - AttributeName: document_type
          AttributeType: S
        - AttributeName: upload_date
          AttributeType: N
      KeySchema:
        - AttributeName: document_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: order_id-index
          KeySchema:
            - AttributeName: order_id
              KeyType: HASH
            - AttributeName: document_type
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: type-date-index
          KeySchema:
            - AttributeName: document_type
              KeyType: HASH
            - AttributeName: upload_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
  
  # 입고 주문 관리 DynamoDB 테이블
  ReceivingOrderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "wms-receiving-orders-${EnvironmentType}-${AWS::StackName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: order_id
          AttributeType: S
        - AttributeName: supplier_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: scheduled_date
          AttributeType: N
        - AttributeName: created_at
          AttributeType: N
      KeySchema:
        - AttributeName: order_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: supplier-index
          KeySchema:
            - AttributeName: supplier_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: status-date-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: scheduled_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: date-status-index
          KeySchema:
            - AttributeName: scheduled_date
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
  
  # 입고 품목 테이블
  ReceivingItemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "wms-receiving-items-${EnvironmentType}-${AWS::StackName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: item_id
          AttributeType: S
        - AttributeName: order_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: N
      KeySchema:
        - AttributeName: item_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: order_id-index
          KeySchema:
            - AttributeName: order_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # 입고 이력 관리 DynamoDB 테이블
  ReceivingHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "wms-receiving-history-${EnvironmentType}-${AWS::StackName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: history_id
          AttributeType: S
        - AttributeName: order_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: history_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: order-time-index
          KeySchema:
            - AttributeName: order_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
  
  # 배포 패키지 저장을 위한 S3 버킷
  DeploymentBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "wms-deployment-${EnvironmentType}-${AWS::AccountId}-${AWS::Region}-${AWS::StackName}-v1"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      

  # 웹 프론트엔드 호스팅을 위한 S3 버킷
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "wms-website-${EnvironmentType}-${AWS::AccountId}-${AWS::Region}-v1"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # 웹 버킷에 대한 공개 액세스 정책
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"

Outputs:
  DocumentBucketName:
    Description: Name of the document S3 bucket
    Value: !Ref DocumentBucket
    Export:
      Name: !Sub "${AWS::StackName}-DocumentBucketName"
  
  DocumentMetadataTableName:
    Description: Name of the document metadata DynamoDB table
    Value: !Ref DocumentMetadataTable
    Export:
      Name: !Sub "${AWS::StackName}-DocumentMetadataTableName"
  
  ReceivingOrderTableName:
    Description: Name of the receiving orders DynamoDB table
    Value: !Ref ReceivingOrderTable
    Export:
      Name: !Sub "${AWS::StackName}-ReceivingOrderTableName"
  
  ReceivingItemTableName:
    Description: Name of the receiving items DynamoDB table
    Value: !Ref ReceivingItemTable
    Export:
      Name: !Sub "${AWS::StackName}-ReceivingItemTableName"
  
  ReceivingHistoryTableName:
    Description: Name of the receiving history DynamoDB table
    Value: !Ref ReceivingHistoryTable
    Export:
      Name: !Sub "${AWS::StackName}-ReceivingHistoryTableName"
  
  DeploymentBucketName:
    Description: Name of the deployment S3 bucket
    Value: !Ref DeploymentBucket
    Export:
      Name: !Sub "${AWS::StackName}-DeploymentBucketName"
  
  WebsiteBucketName:
    Description: Name of the website S3 bucket
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteBucketName"
  
  WebsiteURL:
    Description: URL of the S3 website
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteURL"