AWSTemplateFormatVersion: '2010-09-09'
Description: 'WMS Storage Infrastructure'

Parameters:
  EnvironmentType:
    Description: Environment type
    Type: String
    Default: dev
# (앞서 제공한 YAML 내용으로 채우기)
